
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sendi
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        setUndecorated(true); // Menghilangkan border dan title bar  
        initComponents();
        setFont();
        jTextField1.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "USERNAME");
        jPasswordField1.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "PASSWORD");
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Maksimalkan ke layar penuh  
    }
    private void setFont(){
        try {
            Font fontCustom = Font.createFont(Font.TRUETYPE_FONT,new File("src/Font/Montserrat-Black.ttf")).deriveFont(30f);
            jLabel1.setFont(fontCustom);
            Font Label = Font.createFont(Font.TRUETYPE_FONT,new File("src/Font/Montserrat-Medium.ttf")).deriveFont(18f);
            jLabel2.setFont(Label);
            Font fontButton = Font.createFont(Font.TRUETYPE_FONT,new File("src/Font/Montserrat-Bold.ttf")).deriveFont(17f);
            jButton1.setFont(fontButton);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
     private void validateLogin() {
        String username = jTextField1.getText();
        String password = new String(jPasswordField1.getPassword());
        
        if (username.equals("admin") && password.equals("admin123")) {
            JOptionPane.showMessageDialog(this, "Login Berhasil!");
            new DashboardFrame().setVisible(true); // Form selanjutnya
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Username atau Password salah!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        showpassword = new javax.swing.JLabel();
        hidepassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1058, 704));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/eye-svgrepo-com.png"))); // NOI18N
        showpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpasswordMouseClicked(evt);
            }
        });
        jPanel1.add(showpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 60, 40));

        hidepassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hidepassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/eye-slash-svgrepo-com.png"))); // NOI18N
        hidepassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidepasswordMouseClicked(evt);
            }
        });
        jPanel1.add(hidepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 60, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELAMAT DATANG DI APLIKASI KEPEGAWAIAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Harap Login Terlebih Dahulu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 330, 39));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 330, 39));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 133, 36));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpasswordMouseClicked
        showpassword.setVisible(false);
        hidepassword.setVisible(true);
        jPasswordField1.setEchoChar((char)0);
    }//GEN-LAST:event_showpasswordMouseClicked

    private void hidepasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidepasswordMouseClicked
        showpassword.setVisible(true);
        hidepassword.setVisible(false);
        jPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_hidepasswordMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        validateLogin();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.setup();
        UIManager.put("TableHeader.background", new Color(76,48,36));
        UIManager.put("TableHeader.foreground", Color.white);
        UIManager.put("Table.selectionBackground", Color.black);
        UIManager.put("Component.borderColor", new Color(76,48,36));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hidepassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel showpassword;
    // End of variables declaration//GEN-END:variables
}
